name: deploy-site
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
      pull-requests: write  # To create a PR from that branch
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Setup Node dependencies
        run: npm i

      - name: Build Svelte
        run: npm run build

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: "**index.html"
          find: "/assets"
          replace: "/portfolio/assets"
          regex: false


      - name: Deploy to Github Pages
        run: |
          git worktree add gh-pages
          git config user.name "Deploy from CI"
          git config user.email ""
          cd gh-pages
          git update-ref -d refs/heads/gh-pages
          rm -rf *
          mv ../dist/* .
          git add .
          git commit -m "Deploy $GITHUB_SHA to gh-pages"
          git push --force --set-upstream origin gh-pages